In [32]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable

In [33]:
class Feedforward(nn.Module):
    def __init__(self, input_dim, hidden_dims, output_dim):
        super(Feedforward, self).__init__()
        self.input_dim = input_dim
        self.hidden_dims = hidden_dims
        self.output_dim = output_dim
        self.relu = nn.ReLU()
        
        self.weights = []
        self.biases = []
        dims = [self.input_dim] + self.hidden_dims + [self.output_dim]
        for prev_dim, next_dim in zip(dims, dims[1:]):
            self.weights.append(nn.Parameter(torch.zeros(prev_dim, next_dim)))
            self.biases.append(nn.Parameter(torch.zeros(next_dim,1)))

    def forward(self, x):
        for i, (weight, bias) in enumerate(zip(self.weights, self.biases)):
            print(x)
            x = torch.matmul(weight.t(),x)
            print(x)
            x = torch.add(bias,x)
            if i < len(self.weights) - 1:
                x = self.relu(x)
            print(x)
        return x

In [34]:
input_dim = 5
hidden_dims = [6,7,8]
output_dim = 4
model = Feedforward(input_dim, hidden_dims, output_dim); model

Feedforward(
  (relu): ReLU()
)

In [35]:
model.cuda()

Feedforward(
  (relu): ReLU()
)

In [36]:
t = torch.zeros(5,1)
nn.init.kaiming_uniform_(t)

tensor([[1.4462],
        [0.3503],
        [1.9933],
        [0.4263],
        [0.3117]])

In [37]:
y = model(t)

tensor([[1.4462],
        [0.3503],
        [1.9933],
        [0.4263],
        [0.3117]])
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<MmBackward>)
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<ReluBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<ReluBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<MmBackward>)
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<ReluBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<ReluBackward0>)
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], grad_fn=<MmBackward>)
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        

In [31]:
y

tensor([[0.],
        [0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)